/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumCardIssueRequestRequestStatus } from "./EnumCardIssueRequestRequestStatus";
import { EnumCardIssueRequestSubscriptionType } from "./EnumCardIssueRequestSubscriptionType";

@ObjectType()
class CardIssueRequest {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  businessCode!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  cardRequestId!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  issueDate!: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumCardIssueRequestRequestStatus,
  })
  @IsEnum(EnumCardIssueRequestRequestStatus)
  @IsOptional()
  @Field(() => EnumCardIssueRequestRequestStatus, {
    nullable: true,
  })
  requestStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumCardIssueRequestSubscriptionType,
  })
  @IsEnum(EnumCardIssueRequestSubscriptionType)
  @IsOptional()
  @Field(() => EnumCardIssueRequestSubscriptionType, {
    nullable: true,
  })
  subscriptionType?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  userId!: string | null;
}

export { CardIssueRequest as CardIssueRequest };
